version: "3.1"
services:
  diviner:
    container_name: diviner
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      MONGO_CONNECTION_STRING: mongodb://root:example@mongo:27017/?retryWrites=true&w=majority
      MONGO_DATABASE: diviner
      MONGO_DOMAIN: "mongo"
      MONGO_PASSWORD: example
      MONGO_USERNAME: root

